# generated by datamodel-codegen:
#   filename:  sxplr.navigateTo__toSxplr__request.json
#   timestamp: 2023-12-07T15:40:46+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from .MainState___state import AtlasSelectionNavigation


@dataclass
class Params(AtlasSelectionNavigation):
    animate: Optional[bool] = None


@dataclass
class Model:
    id: Optional[str] = None
    jsonrpc: str = "2.0"
    method: str = "sxplr.navigateTo"
    params: Optional[Params] = None
