# generated by datamodel-codegen:
#   filename:  sxplr.navigateTo__toSxplr__request.json
#   timestamp: 2023-12-07T15:40:46+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class AtlasSelectionNavigation:
    position: Optional[Len3num] = None
    orientation: Optional[Len4num] = None
    zoom: Optional[float] = None
    perspectiveOrientation: Optional[Len4num] = None
    perspectiveZoom: Optional[float] = None


Len3num = List[float]


Len4num = List[float]
