# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/miscellaneous/funding.schema.json
#   timestamp: 2021-11-25T12:27:15+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    acknowledgement: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/acknowledgement',
        description='Offical declaration or avowal of appreciation of an act or achievement.',
        title='acknowledgement',
    )
    awardNumber: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/awardNumber',
        description='Machine-readable identifier for a benefit that is conferred or bestowed on the basis of merit or need.',
        title='awardNumber',
    )
    awardTitle: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/awardTitle',
        description='Human-readable identifier for a benefit that is conferred or bestowed on the basis of merit or need.',
        title='awardTitle',
    )
    funder: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/funder',
        description='Legal person that provides money for a particular purpose.',
        title='funder',
    )
