# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/miscellaneous/GRIDID.schema.json
#   timestamp: 2021-11-25T12:27:13+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    identifier: constr(
        regex=r'^https://grid.ac/institutes/grid.[0-9]{1,}.([a-f0-9]{1,2})$'
    ) = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/identifier',
        description='Term or code used to identify something or someone.',
        title='identifier',
    )
