# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/miscellaneous/quantitativeValueRange.schema.json
#   timestamp: 2021-11-25T12:27:16+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    maxValue: float = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/maxValue',
        description='Greatest quantity attained or allowed.',
        title='maxValue',
    )
    maxValueUnit: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/maxValueUnit',
        title='maxValueUnit',
    )
    minValue: float = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/minValue',
        description='Smallest quantity attained or allowed.',
        title='minValue',
    )
    minValueUnit: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/minValueUnit',
        title='minValueUnit',
    )
