# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/miscellaneous/quantitativeValueRange.schema.json
#   timestamp: 2021-11-29T11:19:33+00:00

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    max_value: float = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/maxValue',
        description='Greatest quantity attained or allowed.',
        title='maxValue',
    )
    max_value_unit: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/maxValueUnit',
        title='maxValueUnit',
    )
    min_value: float = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/minValue',
        description='Smallest quantity attained or allowed.',
        title='minValue',
    )
    min_value_unit: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/minValueUnit',
        title='minValueUnit',
    )
