# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/miscellaneous/quantitativeValue.schema.json
#   timestamp: 2021-11-25T14:29:35+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    type_of_uncertainty: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/typeOfUncertainty',
        description='Distinct technique used to quantify the uncertainty of a measurement.',
        title='typeOfUncertainty',
    )
    uncertainty: Optional[List[float]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/uncertainty',
        description='Quantitative value range defining the uncertainty of a measurement.',
        max_items=2,
        min_items=2,
        title='uncertainty',
    )
    unit: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/unit',
        description='Determinate quantity adopted as a standard of measurement.',
        title='unit',
    )
    value: float = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/value',
        description='Entry for a property.',
        title='value',
    )
