# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/miscellaneous/RORID.schema.json
#   timestamp: 2021-11-25T14:29:33+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    identifier: constr(
        regex=r'^https://ror.org/0([0-9]|[^ILO]|[a-z]){6}[0-9]{2}$'
    ) = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/identifier',
        description='Term or code used to identify something or someone.',
        title='identifier',
    )
