# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/miscellaneous/RRID.schema.json
#   timestamp: 2021-11-29T11:19:32+00:00

from pydantic import BaseModel, Field, constr


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    identifier: constr(
        regex=r'https://scicrunch.org/resolver/RRID:([A-Za-z]+)[_:]([A-Za-z0-9_:-]+)'
    ) = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/identifier',
        description='Term or code used to identify something or someone.',
        title='identifier',
    )
