# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/miscellaneous/stockNumber.schema.json
#   timestamp: 2021-11-29T11:19:34+00:00

from typing import Any, Dict

from pydantic import BaseModel, Field


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    identifier: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/identifier',
        description='Term or code used to identify something or someone.',
        title='identifier',
    )
    vendor: Dict[str, Any] = Field(
        ..., alias='https://openminds.ebrains.eu/vocab/vendor', title='vendor'
    )
