# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/miscellaneous/URL.schema.json
#   timestamp: 2021-11-25T14:29:34+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    url: str = Field(..., alias='https://openminds.ebrains.eu/vocab/URL', title='URL')
