# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/miscellaneous/URL.schema.json
#   timestamp: 2021-11-29T11:19:32+00:00

from pydantic import BaseModel, Field


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    url: str = Field(..., alias='https://openminds.ebrains.eu/vocab/URL', title='URL')
