# generated by datamodel-codegen:
#   filename:  sxplr.getSupportedTemplates__toSxplr__request.json
#   timestamp: 2023-12-07T15:40:43+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional


@dataclass
class Model:
    id: Optional[str] = None
    jsonrpc: str = "2.0"
    method: str = "sxplr.getSupportedTemplates"
    params: Any = None
