image: docker:19.03.8
stages:
  - test
  - build
  - deploy

before-script:
  script:
    - apk update && apk add python pip

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest discover

staging:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

pypi:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
