stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python -m unittest discover

staging:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

pypi:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
