image: docker:stable
stages:
  - test
  - build
  - deploy

before-script:
  - apk add python python-dev python pip

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest discover

staging:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

pypi:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
