# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/controlledTerms/v1/productAccessibility.schema.json
#   timestamp: 2021-11-25T14:29:21+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    definition: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/definition',
        description='Short, but precise statement of the meaning of a word, word group, sign or a symbol.',
        title='definition',
    )
    description: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/description',
        description='Longer statement or account giving the characteristics of someone or something.',
        title='description',
    )
    interlex_identifier: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/interlexIdentifier',
        description='Persistent identifier for a term registered in the InterLex project.',
        title='interlexIdentifier',
    )
    knowledge_space_link: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/knowledgeSpaceLink',
        description='Persistent link to an encyclopedia entry in the Knowledge Space project.',
        title='knowledgeSpaceLink',
    )
    name: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/name',
        description='Word or phrase that constitutes the distinctive designation of a being or thing.',
        title='name',
    )
    preferred_ontology_identifier: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/preferredOntologyIdentifier',
        description='Persistent identifier of a preferred ontological term.',
        title='preferredOntologyIdentifier',
    )
    synonym: Optional[List[str]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/synonym',
        description='Words or expressions used in the same language that have the same or nearly the same meaning in some or all senses.',
        min_items=1,
        title='synonym',
    )
