# generated by datamodel-codegen:
#   filename:  sxplr.on.atlasSelected__fromSxplr__request.json
#   timestamp: 2023-12-07T15:40:36+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class SiibraAtIdModel:
    field_id: str


@dataclass
class PTAtlas:
    field_type: str
    field_id: str
    name: str
    spaces: List[SiibraAtIdModel]
    parcellations: List[SiibraAtIdModel]
    species: str


@dataclass
class Model:
    jsonrpc: str = "2.0"
    method: str = "sxplr.on.atlasSelected"
    params: Optional[PTAtlas] = None
