# generated by datamodel-codegen:
#   filename:  sxplr.getUserToSelectARoi__toSxplr__request.json
#   timestamp: 2023-12-07T15:40:40+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional


@dataclass
class Params:
    type: Optional[Any] = None
    message: Optional[str] = None


@dataclass
class Model:
    id: Optional[str] = None
    jsonrpc: str = '2.0'
    method: str = 'sxplr.getUserToSelectARoi'
    params: Optional[Params] = None
