# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/products/datasetVersion.schema.json
#   timestamp: 2021-11-29T11:19:34+00:00

from datetime import date
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, constr


class Copyright(BaseModel):
    holder: List = Field(
        ...,
        description='Legal person in possession of something.',
        min_items=1,
        title='holder',
    )
    year: constr(regex=r'([0-9]{4})') = Field(
        ...,
        description='Cycle in the Gregorian calendar specified by a number and comprised of 365 or 366 days divided into 12 months beginning with January and ending with December.',
        title='year',
    )


class OtherContribution(BaseModel):
    contribution_type: List = Field(
        ...,
        alias='contributionType',
        description='Distinct class of what was given or supplied as a part or share.',
        min_items=1,
        title='contributionType',
    )
    contributor: Any = Field(
        ...,
        description='Legal person that gave or supplied something as a part or share.',
        title='contributor',
    )


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    accessibility: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/accessibility',
        description='Level to which something is accessible to someone or something.',
        title='accessibility',
    )
    author: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/author',
        description='Creator of a literary or creative work, as well as a dataset publication.',
        min_items=1,
        title='author',
    )
    behavioral_protocol: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/behavioralProtocol',
        min_items=1,
        title='behavioralProtocol',
    )
    copyright: Optional['Copyright'] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/copyright',
        description='Structured information on the copyright.',
    )
    custodian: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/custodian',
        description="The 'custodian' is a legal person who is responsible for the content and quality of the data, metadata, and/or code of a research product.",
        min_items=1,
        title='custodian',
    )
    data_type: List[Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/dataType',
        min_items=1,
        title='dataType',
    )
    description: Optional[constr(max_length=2000)] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/description',
        description='Longer statement or account giving the characteristics of someone or something.',
        title='description',
    )
    digital_identifier: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/digitalIdentifier',
        description='Digital handle to identify objects or legal persons.',
        title='digitalIdentifier',
    )
    ethics_assessment: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/ethicsAssessment',
        description='Judgment about the applied principles of conduct governing an individual or a group.',
        title='ethicsAssessment',
    )
    experimental_approach: List[Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/experimentalApproach',
        min_items=1,
        title='experimentalApproach',
    )
    full_documentation: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/fullDocumentation',
        description='Non-abridged instructions, comments, and information for using a particular product.',
        title='fullDocumentation',
    )
    full_name: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/fullName',
        description='Whole, non-abbreviated name of something or somebody.',
        title='fullName',
    )
    funding: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/funding',
        description='Money provided by a legal person for a particular purpose.',
        min_items=1,
        title='funding',
    )
    homepage: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/homepage',
        description='Main website of something or someone.',
        title='homepage',
    )
    how_to_cite: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/howToCite',
        description='Preferred format for citing a particular object or legal person.',
        title='howToCite',
    )
    input_data: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/inputData',
        description='Data that is put into a process or machine.',
        min_items=1,
        title='inputData',
    )
    is_alternative_version_of: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/isAlternativeVersionOf',
        description='Reference to an original form where the essence was preserved, but presented in an alternative form.',
        min_items=1,
        title='isAlternativeVersionOf',
    )
    is_new_version_of: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/isNewVersionOf',
        description='Reference to a previous (potentially outdated) particular form of something.',
        title='isNewVersionOf',
    )
    keyword: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/keyword',
        description='Significant word or concept that are representative of something or someone.',
        max_items=5,
        min_items=1,
        title='keyword',
    )
    license: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/license',
        description='Grant by a party to another party as an element of an agreement between those parties that permits to do, use, or own something.',
        title='license',
    )
    other_contribution: Optional['OtherContribution'] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/otherContribution',
        description='Structured information on the contribution made to a research product.',
    )
    preparation_design: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/preparationDesign',
        min_items=1,
        title='preparationDesign',
    )
    related_publication: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/relatedPublication',
        description='Reference to something that was made available for the general public to see or buy.',
        min_items=1,
        title='relatedPublication',
    )
    release_date: date = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/releaseDate',
        description='Fixed date on which a product is due to become or was made available for the general public to see or buy',
        title='releaseDate',
    )
    repository: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/repository',
        description='Place, room, or container where something is deposited or stored.',
        title='repository',
    )
    short_name: constr(max_length=30) = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/shortName',
        description='Shortened or fully abbreviated name of something or somebody.',
        title='shortName',
    )
    studied_specimen: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/studiedSpecimen',
        min_items=1,
        title='studiedSpecimen',
    )
    study_target: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/studyTarget',
        description='Structure or function that was targeted within a study.',
        min_items=1,
        title='studyTarget',
    )
    support_channel: Optional[List[str]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/supportChannel',
        description='Way of communication used to interact with users or customers.',
        min_items=1,
        title='supportChannel',
    )
    technique: List[Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/technique',
        description='Method of accomplishing a desired aim.',
        min_items=1,
        title='technique',
    )
    version_identifier: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/versionIdentifier',
        description='Term or code used to identify the version of something.',
        title='versionIdentifier',
    )
    version_innovation: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/versionInnovation',
        description='Documentation on what changed in comparison to a previously published form of something.',
        title='versionInnovation',
    )
