name: '[siibra-cfg] setup custom config'
author: 'Xiao Gui <xgui3783@gmail.com>'
description: 'Setup siibra custom config for tests'
inputs:
  siibra-cfg-ref:
    description: 'git ref of siibra configuration to use'
    required: true
runs:
  using: composite
  steps:
  - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    with:
      repository: 'fzj-inm1-bda/siibra-configurations'
      ref: ${{ inputs.siibra-cfg-ref }}
      path: ${{ github.workspace }}/siibra-configurations
  - id: 'set-env'
    run: |
      echo "SIIBRA_USE_CONFIGURATION=${{ github.workspace }}/siibra-configurations" >> $GITHUB_ENV
    shell: bash
