# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/actors/affiliation.schema.json
#   timestamp: 2021-11-25T14:29:27+00:00

from __future__ import annotations

from datetime import date
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    end_date: Optional[date] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/endDate',
        description='Date in the Gregorian calendar at which something terminates in time.',
        title='endDate',
    )
    organization: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/organization',
        description='Legally accountable, administrative and functional structure.',
        title='organization',
    )
    start_date: Optional[date] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/startDate',
        description='Date in the Gregorian calendar at which something begins in time',
        title='startDate',
    )
