# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/actors/contactInformation.schema.json
#   timestamp: 2021-11-25T14:29:27+00:00

from __future__ import annotations

from pydantic import BaseModel, EmailStr, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    email: EmailStr = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/email',
        description='Address to which or from which an electronic mail can be sent.',
        title='email',
    )
