# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/actors/contribution.schema.json
#   timestamp: 2021-11-25T12:27:09+00:00

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    contributionType: List[Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/contributionType',
        description='Distinct class of what was given or supplied as a part or share.',
        min_items=1,
        title='contributionType',
    )
    contributor: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/contributor',
        description='Legal person that gave or supplied something as a part or share.',
        title='contributor',
    )
