# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/actors/contribution.schema.json
#   timestamp: 2021-11-29T11:19:26+00:00

from typing import Any, Dict, List

from pydantic import BaseModel, Field


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    contribution_type: List[Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/contributionType',
        description='Distinct class of what was given or supplied as a part or share.',
        min_items=1,
        title='contributionType',
    )
    contributor: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/contributor',
        description='Legal person that gave or supplied something as a part or share.',
        title='contributor',
    )
