# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/actors/person.schema.json
#   timestamp: 2021-11-25T14:29:28+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Affiliation(BaseModel):
    end_date: Optional[str] = Field(
        None,
        alias='endDate',
        description='Date in the Gregorian calendar at which something terminates in time.',
        title='endDate',
    )
    organization: Any = Field(
        ...,
        description='Legally accountable, administrative and functional structure.',
        title='organization',
    )
    start_date: Optional[str] = Field(
        None,
        alias='startDate',
        description='Date in the Gregorian calendar at which something begins in time',
        title='startDate',
    )


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    affiliation: Optional[Affiliation] = Field(
        None, alias='https://openminds.ebrains.eu/vocab/affiliation'
    )
    contact_information: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/contactInformation',
        description='Any available way used to contact a person or business (e.g., address, phone number, email address, etc.).',
        title='contactInformation',
    )
    digital_identifier: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/digitalIdentifier',
        description='Digital handle to identify objects or legal persons.',
        min_items=1,
        title='digitalIdentifier',
    )
    family_name: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/familyName',
        description='Name borne in common by members of a family.',
        title='familyName',
    )
    given_name: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/givenName',
        description='Name given to a person, including all potential middle names, but excluding the family name.',
        title='givenName',
    )
