# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/SANDS/v3/atlas/commonCoordinateSpace.schema.json
#   timestamp: 2021-11-29T11:19:02+00:00

from datetime import date
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class AxesOrigin(BaseModel):
    type_of_uncertainty: Optional[Any] = Field(
        None,
        alias='typeOfUncertainty',
        description='Distinct technique used to quantify the uncertainty of a measurement.',
        title='typeOfUncertainty',
    )
    uncertainty: Optional[List[float]] = Field(
        None,
        description='Quantitative value range defining the uncertainty of a measurement.',
        max_items=2,
        min_items=2,
        title='uncertainty',
    )
    unit: Optional[Any] = Field(
        None,
        description='Determinate quantity adopted as a standard of measurement.',
        title='unit',
    )
    value: float = Field(..., description='Entry for a property.', title='value')


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    anatomical_axes_orientation: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/anatomicalAxesOrientation',
        description='Relation between reference planes used in anatomy and mathematics.',
        title='anatomicalAxesOrientation',
    )
    axes_origin: List['AxesOrigin'] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/axesOrigin',
        description='Structured information on a quantitative value.',
    )
    default_image: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/defaultImage',
        description='Two or three dimensional image that particluarly represents a specific coordinate space.',
        min_items=1,
        title='defaultImage',
    )
    digital_identifier: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/digitalIdentifier',
        description='Digital handle to identify objects or legal persons.',
        title='digitalIdentifier',
    )
    full_name: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/fullName',
        description='Whole, non-abbreviated name of something or somebody.',
        title='fullName',
    )
    homepage: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/homepage',
        description='Main website of something or someone.',
        title='homepage',
    )
    how_to_cite: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/howToCite',
        description='Preferred format for citing a particular object or legal person.',
        title='howToCite',
    )
    native_unit: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/nativeUnit',
        description='Determinate quantity used in the original measurement.',
        title='nativeUnit',
    )
    ontology_identifier: Optional[List[str]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/ontologyIdentifier',
        description='Term or code used to identify something or someone registered within a particular ontology.',
        min_items=1,
        title='ontologyIdentifier',
    )
    release_date: date = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/releaseDate',
        description='Fixed date on which a product is due to become or was made available for the general public to see or buy',
        title='releaseDate',
    )
    short_name: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/shortName',
        description='Shortened or fully abbreviated name of something or somebody.',
        title='shortName',
    )
    version_identifier: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/versionIdentifier',
        description='Term or code used to identify the version of something.',
        title='versionIdentifier',
    )
