# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/SANDS/v3/atlas/parcellationTerminologyVersion.schema.json
#   timestamp: 2021-11-25T12:26:48+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    definedIn: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/definedIn',
        description='Reference to a file instance in which something is stored.',
        min_items=1,
        title='definedIn',
    )
    fullName: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/fullName',
        description='Whole, non-abbreviated name of something or somebody.',
        title='fullName',
    )
    hasEntityVersion: List[Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/hasEntityVersion',
        min_items=1,
        title='hasEntityVersion',
    )
    isAlternativeVersionOf: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/isAlternativeVersionOf',
        description='Reference to an original form where the essence was preserved, but presented in an alternative form.',
        min_items=1,
        title='isAlternativeVersionOf',
    )
    isNewVersionOf: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/isNewVersionOf',
        description='Reference to a previous (potentially outdated) particular form of something.',
        title='isNewVersionOf',
    )
    ontologyIdentifier: Optional[List[str]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/ontologyIdentifier',
        description='Term or code used to identify something or someone registered within a particular ontology.',
        min_items=1,
        title='ontologyIdentifier',
    )
    shortName: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/shortName',
        description='Shortened or fully abbreviated name of something or somebody.',
        title='shortName',
    )
    versionIdentifier: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/versionIdentifier',
        description='Term or code used to identify the version of something.',
        title='versionIdentifier',
    )
    versionInnovation: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/versionInnovation',
        description='Documentation on what changed in comparison to a previously published form of something.',
        title='versionInnovation',
    )
