# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
- name: '❓ Neurostars'
  url: https://neurostars.org/tag/siibra/753
  about: |
    Ask a question about siibra-python on Neurostars.