name: '📖 Documentation'
description: Report an issue with the documentation.
labels: [documentation]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Please describe the issue with documentation.
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link
      description: >
        Provide a link to the existing documentation, if applicable.
      placeholder: ex. https://siibra-python.readthedocs.io/...
    validations:
      required: false