# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/computation/v1/environment.schema.json
#   timestamp: 2021-11-25T12:26:51+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    configuration: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/configuration',
        min_items=1,
        title='configuration',
    )
    description: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/description',
        description='Longer statement or account giving the characteristics of someone or something.',
        title='description',
    )
    hardware: Dict[str, Any] = Field(
        ..., alias='https://openminds.ebrains.eu/vocab/hardware', title='hardware'
    )
    name: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/name',
        description='Word or phrase that constitutes the distinctive designation of a being or thing.',
        title='name',
    )
    software: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/software',
        min_items=1,
        title='software',
    )
