# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/computation/v1/launchConfiguration.schema.json
#   timestamp: 2021-11-25T12:26:52+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    arguments: Optional[List[str]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/arguments',
        min_items=1,
        title='arguments',
    )
    description: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/description',
        description='Longer statement or account giving the characteristics of someone or something.',
        title='description',
    )
    environmentVariables: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/environmentVariables',
        title='environmentVariables',
    )
    executable: str = Field(
        ..., alias='https://openminds.ebrains.eu/vocab/executable', title='executable'
    )
    name: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/name',
        description='Word or phrase that constitutes the distinctive designation of a being or thing.',
        title='name',
    )
