# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/computation/v1/workflowExecution.schema.json
#   timestamp: 2021-11-29T11:19:09+00:00

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    stages: Dict[str, Any] = Field(
        ..., alias='https://openminds.ebrains.eu/vocab/stages', title='stages'
    )
    started_by: Optional[Dict[str, Any]] = Field(
        None, alias='https://openminds.ebrains.eu/vocab/startedBy', title='startedBy'
    )
