# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/data/contentTypePattern.schema.json
#   timestamp: 2021-11-25T12:27:10+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    contentType: Dict[str, Any] = Field(
        ..., alias='https://openminds.ebrains.eu/vocab/contentType', title='contentType'
    )
    lookupLabel: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/lookupLabel',
        title='lookupLabel',
    )
    regex: str = Field(
        ..., alias='https://openminds.ebrains.eu/vocab/regex', title='regex'
    )
