# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/data/copyright.schema.json
#   timestamp: 2021-11-25T14:29:29+00:00

from __future__ import annotations

from typing import Any, List

from pydantic import BaseModel, Field, constr


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    holder: List[Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/holder',
        description='Legal person in possession of something.',
        min_items=1,
        title='holder',
    )
    year: constr(regex=r'([0-9]{4})') = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/year',
        description='Cycle in the Gregorian calendar specified by a number and comprised of 365 or 366 days divided into 12 months beginning with January and ending with December.',
        title='year',
    )
