# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/data/fileRepositoryStructure.schema.json
#   timestamp: 2021-11-25T14:29:31+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field


class FilePathPattern(BaseModel):
    grouping_type: Any = Field(..., alias='groupingType', title='groupingType')
    regex: str = Field(..., title='regex')


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    file_path_pattern: FilePathPattern = Field(
        ..., alias='https://openminds.ebrains.eu/vocab/filePathPattern'
    )
    lookup_label: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/lookupLabel',
        title='lookupLabel',
    )
