# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/data/filePathPattern.schema.json
#   timestamp: 2021-11-29T11:19:29+00:00

from typing import Any, Dict

from pydantic import BaseModel, Field


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    grouping_type: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/groupingType',
        title='groupingType',
    )
    regex: str = Field(
        ..., alias='https://openminds.ebrains.eu/vocab/regex', title='regex'
    )
