# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/data/file.schema.json
#   timestamp: 2021-11-25T12:27:11+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Hash(BaseModel):
    algorithm: str = Field(
        ...,
        description='Procedure for solving a mathematical problem in a finite number of steps. Can involve repetition of an operation.',
        title='algorithm',
    )
    digest: str = Field(
        ...,
        description='Summation or condensation of a body of information.',
        title='digest',
    )


class StorageSize(BaseModel):
    typeOfUncertainty: Optional[Any] = Field(
        None,
        description='Distinct technique used to quantify the uncertainty of a measurement.',
        title='typeOfUncertainty',
    )
    uncertainty: Optional[List[float]] = Field(
        None,
        description='Quantitative value range defining the uncertainty of a measurement.',
        max_items=2,
        min_items=2,
        title='uncertainty',
    )
    unit: Optional[Any] = Field(
        None,
        description='Determinate quantity adopted as a standard of measurement.',
        title='unit',
    )
    value: float = Field(..., description='Entry for a property.', title='value')


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    IRI: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/IRI',
        description='Stands for Internationalized Resource Identifier which is an internet protocol standard that builds on the URI protocol, extending the set of permitted characters to include Unicode/ISO 10646.',
        title='IRI',
    )
    contentDescription: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/contentDescription',
        title='contentDescription',
    )
    dataType: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/dataType',
        min_items=1,
        title='dataType',
    )
    fileRepository: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/fileRepository',
        title='fileRepository',
    )
    format: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/format',
        description='Method of digitally organizing and structuring data or information.',
        title='format',
    )
    hash: Optional[Hash] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/hash',
        description='Structured information on a hash.',
    )
    isPartOf: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/isPartOf',
        description='Reference to the ensemble of multiple things or beings.',
        min_items=1,
        title='isPartOf',
    )
    name: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/name',
        description='Word or phrase that constitutes the distinctive designation of a being or thing.',
        title='name',
    )
    specialUsageRole: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/specialUsageRole',
        description='Particular function of something when it is used.',
        title='specialUsageRole',
    )
    storageSize: Optional[StorageSize] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/storageSize',
        description='Structured information on a quantitative value.',
    )
