# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/data/filePathPattern.schema.json
#   timestamp: 2021-11-25T12:27:11+00:00

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    groupingType: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/groupingType',
        title='groupingType',
    )
    regex: str = Field(
        ..., alias='https://openminds.ebrains.eu/vocab/regex', title='regex'
    )
