# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/data/hash.schema.json
#   timestamp: 2021-11-25T12:27:12+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    algorithm: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/algorithm',
        description='Procedure for solving a mathematical problem in a finite number of steps. Can involve repetition of an operation.',
        title='algorithm',
    )
    digest: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/digest',
        description='Summation or condensation of a body of information.',
        title='digest',
    )
