# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/data/license.schema.json
#   timestamp: 2021-11-29T11:19:30+00:00

from typing import List, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    full_name: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/fullName',
        description='Whole, non-abbreviated name of something or somebody.',
        title='fullName',
    )
    legal_code: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/legalCode',
        description='Type of legislation that claims to cover the law system (complete or parts) as it existed at the time the code was enacted.',
        title='legalCode',
    )
    short_name: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/shortName',
        description='Shortened or fully abbreviated name of something or somebody.',
        title='shortName',
    )
    webpage: Optional[List[str]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/webpage',
        description='Hypertext document (block of information) found on the World Wide Web.',
        min_items=1,
        title='webpage',
    )
