# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/3fa86f956b407b2debf47c2e1b6314e37579c707/v3/core/v4/data/serviceLink.schema.json

from typing import Any, Dict, Optional

from pydantic import Field
from siibra.openminds.base import SiibraBaseModel


class Model(SiibraBaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    data_location: Dict[str, Any] = Field(
        ...,
        alias='dataLocation',
        title='dataLocation',
    )
    name: Optional[str] = Field(
        None,
        alias='name',
        description='Word or phrase that constitutes the distinctive designation of a being or thing.',
        title='name',
    )
    open_data_in: Dict[str, Any] = Field(
        ..., alias='openDataIn', title='openDataIn'
    )
    service: Dict[str, Any] = Field(
        ..., alias='service', title='service'
    )
