# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/data/serviceLink.schema.json
#   timestamp: 2021-11-29T11:19:30+00:00

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    data_location: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/dataLocation',
        title='dataLocation',
    )
    name: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/name',
        description='Word or phrase that constitutes the distinctive designation of a being or thing.',
        title='name',
    )
    open_data_in: Dict[str, Any] = Field(
        ..., alias='https://openminds.ebrains.eu/vocab/openDataIn', title='openDataIn'
    )
    service: Dict[str, Any] = Field(
        ..., alias='https://openminds.ebrains.eu/vocab/service', title='service'
    )
