# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/research/behavioralProtocol.schema.json
#   timestamp: 2021-11-29T11:19:37+00:00

from typing import Any, List, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    id: str = Field(..., alias='@id', description='Metadata node identifier.')
    type: str = Field(..., alias='@type')
    description: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/description',
        description='Longer statement or account giving the characteristics of someone or something.',
        title='description',
    )
    internal_identifier: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/internalIdentifier',
        description='Term or code that identifies someone or something within a particular product.',
        title='internalIdentifier',
    )
    name: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/name',
        description='Word or phrase that constitutes the distinctive designation of a being or thing.',
        title='name',
    )
    stimulation: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/stimulation',
        min_items=1,
        title='stimulation',
    )
