# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/research/protocolExecution.schema.json
#   timestamp: 2021-11-25T12:27:21+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


class ValueItem(BaseModel):
    typeOfUncertainty: Optional[Any] = Field(
        None,
        description='Distinct technique used to quantify the uncertainty of a measurement.',
        title='typeOfUncertainty',
    )
    uncertainty: Optional[List[float]] = Field(
        None,
        description='Quantitative value range defining the uncertainty of a measurement.',
        max_items=2,
        min_items=2,
        title='uncertainty',
    )
    unit: Optional[Any] = Field(
        None,
        description='Determinate quantity adopted as a standard of measurement.',
        title='unit',
    )
    value: float = Field(..., description='Entry for a property.', title='value')


class ValueItem1(BaseModel):
    maxValue: float = Field(
        ..., description='Greatest quantity attained or allowed.', title='maxValue'
    )
    maxValueUnit: Optional[Any] = Field(None, title='maxValueUnit')
    minValue: float = Field(
        ..., description='Smallest quantity attained or allowed.', title='minValue'
    )
    minValueUnit: Optional[Any] = Field(None, title='minValueUnit')


class ParameterItem(BaseModel):
    name: str = Field(
        ...,
        description='Word or phrase that constitutes the distinctive designation of a being or thing.',
        title='name',
    )
    value: Union[ValueItem, ValueItem1]


class ParameterItem1(BaseModel):
    name: str = Field(
        ...,
        description='Word or phrase that constitutes the distinctive designation of a being or thing.',
        title='name',
    )
    value: str = Field(..., description='Entry for a property.', title='value')


class ParameterSet(BaseModel):
    context: str = Field(..., title='context')
    parameter: Union[ParameterItem, ParameterItem1]
    relevantFor: Any = Field(
        ...,
        description='Reference to what or whom something or someone bears siginificance.',
        title='relevantFor',
    )


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    behavioralProtocol: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/behavioralProtocol',
        min_items=1,
        title='behavioralProtocol',
    )
    description: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/description',
        description='Longer statement or account giving the characteristics of someone or something.',
        title='description',
    )
    endedAtTime: Optional[Union[Any, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/endedAtTime',
        title='endedAtTime',
    )
    input: List[Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/input',
        description='Something or someone that is put into or participates in a process or machine.',
        min_items=1,
        title='input',
    )
    isPartOf: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/isPartOf',
        description='Reference to the ensemble of multiple things or beings.',
        title='isPartOf',
    )
    lookupLabel: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/lookupLabel',
        title='lookupLabel',
    )
    output: List[Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/output',
        description='Something or someone that comes out of, is delivered or produced by a process or machine.',
        min_items=1,
        title='output',
    )
    parameterSet: Optional[ParameterSet] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/parameterSet',
        description='Structured information on a used parameter set.',
    )
    preparationDesign: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/preparationDesign',
        title='preparationDesign',
    )
    protocol: List[Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/protocol',
        description='Plan that describes the process of a scientific or medical experiment, treatment, or procedure.',
        min_items=1,
        title='protocol',
    )
    startedAtTime: Optional[Union[Any, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/startedAtTime',
        title='startedAtTime',
    )
    studyTarget: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/studyTarget',
        description='Structure or function that was targeted within a study.',
        min_items=1,
        title='studyTarget',
    )
