# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/research/stimulation.schema.json
#   timestamp: 2021-11-25T14:29:41+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    description: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/description',
        description='Longer statement or account giving the characteristics of someone or something.',
        title='description',
    )
    lookup_label: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/lookupLabel',
        title='lookupLabel',
    )
    stimulation_approach: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/stimulationApproach',
        title='stimulationApproach',
    )
    stimulus_type: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/stimulusType',
        title='stimulusType',
    )
