# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/core/v4/research/strain.schema.json
#   timestamp: 2021-11-25T12:27:21+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, constr


class StockNumber(BaseModel):
    identifier: str = Field(
        ...,
        description='Term or code used to identify something or someone.',
        title='identifier',
    )
    vendor: Any = Field(..., title='vendor')


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    RRID: Optional[Dict[str, Any]] = Field(
        None, alias='https://openminds.ebrains.eu/vocab/RRID', title='RRID'
    )
    backgroundStrain: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/backgroundStrain',
        max_items=2,
        min_items=1,
        title='backgroundStrain',
    )
    breedingType: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/breedingType',
        title='breedingType',
    )
    description: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/description',
        description='Longer statement or account giving the characteristics of someone or something.',
        title='description',
    )
    diseaseModel: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/diseaseModel',
        min_items=1,
        title='diseaseModel',
    )
    geneticStrainType: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/geneticStrainType',
        title='geneticStrainType',
    )
    identifier: Optional[List[str]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/identifier',
        description='Term or code used to identify something or someone.',
        min_items=1,
        title='identifier',
    )
    laboratoryCode: Optional[constr(regex=r'^[A-Z]([a-z]?)+$')] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/laboratoryCode',
        title='laboratoryCode',
    )
    name: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/name',
        description='Word or phrase that constitutes the distinctive designation of a being or thing.',
        title='name',
    )
    ontologyIdentifier: Optional[List[str]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/ontologyIdentifier',
        description='Term or code used to identify something or someone registered within a particular ontology.',
        min_items=1,
        title='ontologyIdentifier',
    )
    phenotype: Optional[str] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/phenotype',
        description='Physical expression of one or more genes of an organism.',
        title='phenotype',
    )
    species: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/species',
        description='Category of biological classification comprising related organisms or populations potentially capable of interbreeding, and being designated by a binomial that consists of the name of a genus followed by a Latin or latinized uncapitalized noun or adjective.',
        title='species',
    )
    stockNumber: Optional[StockNumber] = Field(
        None, alias='https://openminds.ebrains.eu/vocab/stockNumber'
    )
    synonym: Optional[List[str]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/synonym',
        description='Words or expressions used in the same language that have the same or nearly the same meaning in some or all senses.',
        min_items=1,
        title='synonym',
    )
