# generated by datamodel-codegen:
#   filename:  sxplr.getSupportedTemplates__toSxplr__response.json
#   timestamp: 2023-12-07T15:40:37+00:00

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union


@dataclass
class VocabModel:
    field_vocab: str


@dataclass
class EbrainsDsPerson:
    field_type: str
    field_id: str
    schema_org_shortName: str
    identifier: str
    shortName: str
    name: str


@dataclass
class EbrainsDsUrl:
    field_type: str
    url: str


@dataclass
class SiibraAtIdModel:
    field_id: str


@dataclass
class AxesOrigin:
    value: float
    field_context: Optional[VocabModel] = field(
        default_factory=lambda: {'@vocab': 'https://openminds.ebrains.eu/vocab/'}
    )
    typeOfUncertainty: Optional[Any] = None
    uncertainty: Optional[List[float]] = None
    unit: Optional[Any] = None


@dataclass
class EbrainsDatasetModel:
    field_type: str
    field_id: str
    name: str
    urls: List[EbrainsDsUrl]
    contributors: List[EbrainsDsPerson]
    custodians: List[EbrainsDsPerson]
    description: Optional[str] = None
    ebrains_page: Optional[str] = None


@dataclass
class VolumeModel:
    field_type: str
    name: str
    formats: List[str]
    providesMesh: bool
    providesImage: bool
    fragments: Dict[str, List[str]]
    providedVolumes: Dict[str, Union[str, Dict[str, str]]]
    space: SiibraAtIdModel
    datasets: List[EbrainsDatasetModel]
    variant: Optional[str] = None


@dataclass
class PTSpace:
    field_type: str
    field_id: str
    anatomicalAxesOrientation: Dict[str, Any]
    axesOrigin: List[AxesOrigin]
    fullName: str
    nativeUnit: Dict[str, Any]
    releaseDate: str
    shortName: str
    versionIdentifier: str
    field_context: Optional[VocabModel] = field(
        default_factory=lambda: {'@vocab': 'https://openminds.ebrains.eu/vocab/'}
    )
    defaultImage: Optional[List[VolumeModel]] = None
    digitalIdentifier: Optional[Dict[str, Any]] = None
    homepage: Optional[Dict[str, Any]] = None
    howToCite: Optional[str] = None
    ontologyIdentifier: Optional[List[str]] = None
    datasets: Optional[List[EbrainsDatasetModel]] = None


@dataclass
class Model:
    jsonrpc: str = '2.0'
    id: Optional[str] = None
    result: Optional[List[PTSpace]] = None
