# generated by datamodel-codegen:
#   filename:  sxplr.getUserToSelectARoi__toSxplr__response.json
#   timestamp: 2023-12-07T15:40:45+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, List, Optional, Union


@dataclass
class Space:
    id: Optional[str] = None


@dataclass
class Point:
    loc: Optional[List[float]] = None
    space: Optional[Space] = None


PTRegion = Any


@dataclass
class Model:
    jsonrpc: str = '2.0'
    id: Optional[str] = None
    result: Optional[Union[PTRegion, Point]] = None
