# generated by datamodel-codegen:
#   filename:  sxplr.rmAnnotations__toSxplr__request.json
#   timestamp: 2023-12-07T15:40:39+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class AtId:
    field_id: Optional[str] = None


@dataclass
class Params:
    annotations: Optional[List[AtId]] = None


@dataclass
class Model:
    id: Optional[str] = None
    jsonrpc: str = '2.0'
    method: str = 'sxplr.rmAnnotations'
    params: Optional[Params] = None
