# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/SANDS/v3/miscellaneous/quantitativeRelationAssessment.schema.json
#   timestamp: 2021-11-25T12:26:49+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


class QuantitativeOverlapItem(BaseModel):
    typeOfUncertainty: Optional[Any] = Field(
        None,
        description='Distinct technique used to quantify the uncertainty of a measurement.',
        title='typeOfUncertainty',
    )
    uncertainty: Optional[List[float]] = Field(
        None,
        description='Quantitative value range defining the uncertainty of a measurement.',
        max_items=2,
        min_items=2,
        title='uncertainty',
    )
    unit: Optional[Any] = Field(
        None,
        description='Determinate quantity adopted as a standard of measurement.',
        title='unit',
    )
    value: float = Field(..., description='Entry for a property.', title='value')


class QuantitativeOverlapItem1(BaseModel):
    maxValue: float = Field(
        ..., description='Greatest quantity attained or allowed.', title='maxValue'
    )
    maxValueUnit: Optional[Any] = Field(None, title='maxValueUnit')
    minValue: float = Field(
        ..., description='Smallest quantity attained or allowed.', title='minValue'
    )
    minValueUnit: Optional[Any] = Field(None, title='minValueUnit')


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    criteria: Optional[Dict[str, Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/criteria',
        description='Aspects or standards on which a judgement or decision is based.',
        title='criteria',
    )
    inRelationTo: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/inRelationTo',
        description='Reference to a related element.',
        title='inRelationTo',
    )
    quantitativeOverlap: Union[
        QuantitativeOverlapItem, QuantitativeOverlapItem1
    ] = Field(..., alias='https://openminds.ebrains.eu/vocab/quantitativeOverlap')
