# generated by datamodel-codegen:
#   filename:  sxplr.init__fromSxplr__request.json
#   timestamp: 2023-12-07T15:40:35+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Result:
    name: Optional[str] = None


@dataclass
class Model:
    jsonrpc: str = "2.0"
    id: Optional[str] = None
    result: Optional[Result] = None
