# generated by datamodel-codegen:
#   filename:  sxplr.addAnnotations__toSxplr__request.json
#   timestamp: 2023-12-08T16:22:30+00:00

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class AtId:
    field_id: Optional[str] = None


@dataclass
class VocabModel:
    field_vocab: str


@dataclass
class ApiModelsOpenmindsSANDSV3MiscellaneousCoordinatePointCoordinates:
    value: float
    field_context: Optional[VocabModel] = field(
        default_factory=lambda: {"@vocab": "https://openminds.ebrains.eu/vocab/"}
    )
    typeOfUncertainty: Optional[Any] = None
    uncertainty: Optional[List[float]] = None
    unit: Optional[Any] = None


@dataclass
class CoordinatePointModel:
    field_type: str
    field_id: str
    coordinateSpace: Dict[str, Any]
    coordinates: List[ApiModelsOpenmindsSANDSV3MiscellaneousCoordinatePointCoordinates]
    field_context: Optional[VocabModel] = field(
        default_factory=lambda: {"@vocab": "https://openminds.ebrains.eu/vocab/"}
    )


@dataclass
class SxplrCoordinatePointExtension(AtId):
    name: Optional[str] = None
    color: Optional[str] = None
    openminds: Optional[CoordinatePointModel] = None


@dataclass
class Params:
    annotations: Optional[List[SxplrCoordinatePointExtension]] = None


@dataclass
class Model:
    id: Optional[str] = None
    jsonrpc: str = "2.0"
    method: str = "sxplr.addAnnotations"
    params: Optional[Params] = None
