# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/HumanBrainProject/openMINDS/dbb4c54/v3/SANDS/v3/non-atlas/customCoordinateSpace.schema.json
#   timestamp: 2021-11-25T12:26:51+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class AxesOrigin(BaseModel):
    typeOfUncertainty: Optional[Any] = Field(
        None,
        description='Distinct technique used to quantify the uncertainty of a measurement.',
        title='typeOfUncertainty',
    )
    uncertainty: Optional[List[float]] = Field(
        None,
        description='Quantitative value range defining the uncertainty of a measurement.',
        max_items=2,
        min_items=2,
        title='uncertainty',
    )
    unit: Optional[Any] = Field(
        None,
        description='Determinate quantity adopted as a standard of measurement.',
        title='unit',
    )
    value: float = Field(..., description='Entry for a property.', title='value')


class Model(BaseModel):
    _id: str = Field(..., alias='@id', description='Metadata node identifier.')
    _type: str = Field(..., alias='@type')
    anatomicalAxesOrientation: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/anatomicalAxesOrientation',
        description='Relation between reference planes used in anatomy and mathematics.',
        title='anatomicalAxesOrientation',
    )
    axesOrigin: AxesOrigin = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/axesOrigin',
        description='Structured information on a quantitative value.',
    )
    defaultImage: Optional[List[Any]] = Field(
        None,
        alias='https://openminds.ebrains.eu/vocab/defaultImage',
        description='Two or three dimensional image that particluarly represents a specific coordinate space.',
        min_items=1,
        title='defaultImage',
    )
    name: str = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/name',
        description='Word or phrase that constitutes the distinctive designation of a being or thing.',
        title='name',
    )
    nativeUnit: Dict[str, Any] = Field(
        ...,
        alias='https://openminds.ebrains.eu/vocab/nativeUnit',
        description='Determinate quantity used in the original measurement.',
        title='nativeUnit',
    )
