# generated by datamodel-codegen:
#   filename:  sxplr.exit__toSxplr__request.json
#   timestamp: 2023-12-07T15:40:44+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class JRPCRequest:
    id: Optional[str] = None


@dataclass
class Params:
    requests: Optional[List[JRPCRequest]] = None


@dataclass
class Model:
    id: Optional[str] = None
    jsonrpc: str = "2.0"
    method: str = "sxplr.exit"
    params: Optional[Params] = None
