# generated by datamodel-codegen:
#   filename:  sxplr.removeLayers__toSxplr__request.json
#   timestamp: 2023-12-07T15:40:38+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class Layer:
    id: Optional[str] = None


@dataclass
class Params:
    layers: Optional[List[Layer]] = None


@dataclass
class Model:
    id: Optional[str] = None
    jsonrpc: str = "2.0"
    method: str = "sxplr.removeLayers"
    params: Optional[Params] = None
