name: e2e Test
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      use-cfg:
        required: false
        type: string
        default: ''
      siibra_log_level:
        required: False
        type: string
        default: "INFO_WO_PROGRESS_BARS"

jobs:
  e2e:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - if: ${{ inputs.use-cfg != '' }}
      uses: './.github/workflows/setup-custom-cfg'
      with:
        siibra-cfg-ref: ${{ inputs.use-cfg }}
        
    - name: Set env vars
      run: echo "SIIBRA_LOG_LEVEL=${{ inputs.siibra_log_level }}" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U .
        pip install -r requirements-test.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install test dependencies
      run:  pip install pytest pytest-cov coverage
    - name: Run test with pytest
      shell: bash
      run: pytest -rx e2e
