name: '[cron] test siibra-tutorials'

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 1,11,21 * *' # every 1st, 11th, and 21th of every month at 6:30

jobs:
  test_tutorials:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # 7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U .
          pip install siibra_jugex
          pip install matplotlib
          pip install pytest nbmake

      - name: checkout siibra-tutorials
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # 7.0.1
        with:
          repository: FZJ-INM1-BDA/siibra-tutorials
          path:  siibra-tutorials-${{ github.run_id }}-${{ github.run_number }}
          fetch-depth: 1
          clean: True
          ref: 'main'
      
      - name: Test tutorial notebooks with nbmake
        run: pytest --nbmake --nbmake-timeout=2000 ./siibra-tutorials-${{ github.run_id }}-${{ github.run_number }}
