name: '[build] build and push docker images'

on:
  release:
    types:
      - created

jobs:
  build-docker-img:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-repo: [ 'docker-registry.ebrains.eu' ]
        docker-file: [ 'Dockerfile' ]
    steps:
    - uses: actions/checkout@v4
    - name: 'Set env var'
      run: |
        
        SIIBRA_VERSION=$(cat siibra/VERSION)

        if [ ${{ matrix.docker-file }} == 'Dockerfile' ]
        then
          DOCKER_TAG=siibra/siibra-python:jupyter-${SIIBRA_VERSION}
          LATEST_TAG=siibra/siibra-python:latest
        else
          echo Unknown docker-file configuration: ${{ matrix.docker-file }}
          return 1
        fi

        if [ ! -z "${{ matrix.docker-repo }}" ]
        then
          DOCKER_TAG=${{ matrix.docker-repo }}/${DOCKER_TAG}
          LATEST_TAG=${{ matrix.docker-repo }}/${LATEST_TAG}
        fi

        echo "siibra-version: $SIIBRA_VERSION , docker tag: $DOCKER_TAG"

        echo "SIIBRA_VERSION=$SIIBRA_VERSION" >> $GITHUB_ENV
        echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: 'Build docker image'
      run: |
        docker build -t $DOCKER_TAG -f ${{ matrix.docker-file }} .
        docker tag $DOCKER_TAG $LATEST_TAG
        docker images

    - name: 'Publish repo'
      run: |
        if [ ! -z "${{ matrix.docker-repo }}" ]
        then
          docker login \
            -u '${{ secrets.EBRAINS_DOCKER_REPO_IMAGE_PUSHER_NAME }}' \
            -p '${{ secrets.EBRAINS_DOCKER_REPO_IMAGE_PUSHER }}' \
            ${{ matrix.docker-repo }}
        fi

        docker push $DOCKER_TAG
        docker push $LATEST_TAG
