name: '[Docs] Build docs and upload artifacts'

on:
  push:
    branches: [ 'main', 'doc_*', 'v1' ]
  release:
    types: [ 'published' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  notebooks:
    name: "Build and run the notebooks for the docs"
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U .
          python -m pip install -r ./docs/requirements-doc.txt

      - name: Build the docs and execute the notebooks
        run: |
          sphinx-build docs ./docs/_build/

      - name: Upload built docs artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: sphinx-docs-built-in-github-${{ github.sha }}
          path: docs
          retention-days: 7

  upload-to-rtd:
    name: "Trigger RTD build"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    needs: notebooks
    steps:
      - name: Trigger RTD build
        uses: dfm/rtds-action@e028de3bdec9ae8e4bda371425986df0fb6cc4bf  # v1.1.0
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}

  cleanup:
    name: "Clean up build artifacts and siibra cache"
    runs-on: self-hosted
    permissions: {}
    needs: [notebooks, upload-to-rtd]
    if: always()
    steps:
      - name: Remove checked-out repository files
        continue-on-error: true
        run: |
          rm -rf ${{ github.workspace }}/*
          rm -rf /tmp/*