# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: '[release] Publish release to pypi'

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
      KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U .
        pip install -r requirements-test.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Build the package
      run: |
        echo "Installing and upgrading twine, setuptools and wheel"
        python -m pip install --user --upgrade twine setuptools wheel
        echo "Package the project"
        python setup.py sdist bdist_wheel
    - name: Prepare pypi settings
      run: |
        echo "[pypi]" >~/.pypirc
        echo "username = __token__" >>~/.pypirc
        echo "password = ${{ secrets.PYPI_PUSH }}" >>~/.pypirc
    - name: Upload to pypi
      run: |
        echo "Uploading to pypi"
        python -m twine upload dist/*
