name: '[python-package]'

on: [ 'push' ]
jobs:
  check-importable:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', '3.7', '3.6' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U .
    
    - name: cd to / and try to import
      run: |
        cd / && python -c 'import siibra'