name: "[test] unit test"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  USE_CONFIG_COMMIT_KW: "[ci:usecfg]"
  SIIBRA_LOG_LEVEL: "INFO_WO_PROGRESS_BARS"

jobs:
  use-custom-cfg:
    runs-on: ubuntu-latest
    outputs:
      USE_REF: ${{ steps.use-ref.outputs.USE_REF }}
    env:
      # see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
      COMMIT_MSG: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v4
      - id: "use-ref"
        run: |
          SED_S_PATTERN=$(echo '${{ env.USE_CONFIG_COMMIT_KW }}' | sed 's/\[/\\[/' | sed 's/]/\\]/')
          echo "$COMMIT_MSG" | while IFS= read -r line
          do
            if [[ "$line" == "${{ env.USE_CONFIG_COMMIT_KW }}"* ]]
            then
              echo "Found usecfg line in commit message: $line"
              USE_REF=$(echo $line | sed "s/$SED_S_PATTERN *//")
              echo "Use Ref: $USE_REF"
              echo USE_REF=$USE_REF >> $GITHUB_OUTPUT
            fi
          done

  lint:
    uses: ./.github/workflows/_lint.yaml
    with:
      os: ubuntu-latest
      python-version: "3.8"

  check-importable:
    needs: "use-custom-cfg"
    uses: ./.github/workflows/_importable.yaml
    with:
      os: ubuntu-22.04  # use ubuntu-latest when python 3.8 is dropped
      python-version: ${{ matrix.python-version }}
      use-cfg: ${{ needs.use-custom-cfg.outputs.USE_REF }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8"]

  unit-tests-full:
    if: ${{ github.event_name == 'pull_request' }}
    needs: "use-custom-cfg"
    uses: ./.github/workflows/_unittest.yaml
    with:
      os: ubuntu-22.04  # use ubuntu-latest when python 3.8 is dropped
      python-version: ${{ matrix.python-version }}
      use-cfg: ${{ needs.use-custom-cfg.outputs.USE_REF }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8"]

  unit-tests-fast:
    if: ${{ github.event.pull_request == null }}
    needs: "use-custom-cfg"
    uses: ./.github/workflows/_unittest.yaml
    with:
      os: ubuntu-latest
      python-version: "3.8"
      use-cfg: ${{ needs.use-custom-cfg.outputs.USE_REF }}

  e2e-tests-full:
    if: ${{ github.event_name == 'pull_request' }}
    needs: "use-custom-cfg"
    uses: ./.github/workflows/_e2e.yaml
    with:
      os: ubuntu-22.04  # use ubuntu-latest when python 3.8 is dropped
      python-version: ${{ matrix.python-version }}
      use-cfg: ${{ needs.use-custom-cfg.outputs.USE_REF }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8"]

  get-e2e-folders:
    runs-on: ubuntu-latest
    outputs:
      e2e_paths: ${{ steps.forward.outputs.e2e_paths }}
    steps:
      - uses: actions/checkout@v4
      - name: find test paths
        id: find_paths
        run: |
          entries=$(
            find e2e -type f -name 'test_*.py' -printf '%h\n' | sort -u | while read dir; do
              if (find "$dir" -maxdepth 1 -type f -name 'test_*.py' | grep -q .) && (find "$dir" -mindepth 1 -type d -name '[a-z]*' | grep -q .); then
                find "$dir" -maxdepth 1 -type f -name 'test_*.py' | sort | xargs
              else
                echo "$dir"
              fi
            done
          )
          json=$(printf '%s\n' $entries | jq -R . | jq -s -c .)
          echo "e2e_paths=$json" >> $GITHUB_OUTPUT
      
      - name: forward output
        id: forward
        run: echo "e2e_paths=${{ steps.find_paths.outputs.e2e_paths }}" >> $GITHUB_OUTPUT

  e2e-tests-fast:
    needs: ["get-e2e-folders", "use-custom-cfg"]
    strategy:
      matrix:
        test_folder: ${{ fromJson(needs.get-e2e-folders.outputs.e2e_paths) }}
    uses: ./.github/workflows/_e2e.yaml
    with:
      os: ubuntu-latest
      python-version: "3.8"
      use-cfg: ${{ needs.use-custom-cfg.outputs.USE_REF }}
      test_folder: ${{ matrix.test_folder }}
    


  test-examples:
    needs: 'use-custom-cfg'
    uses: ./.github/workflows/_run_examples.yaml
    with:
      os: ubuntu-latest
      python-version: "3.8"
      use-cfg: ${{ needs.use-custom-cfg.outputs.USE_REF }}