name: '[test] unit test'

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  lint:
    uses: ./.github/workflows/_lint.yml
    with:
      os: ubuntu-latest
      python-version: '3.8'

  check-importable:
    uses: ./.github/workflows/_importable.yml
    with:
      os: ubuntu-latest
      python-version: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.12', '3.11', '3.10', '3.9', '3.8', '3.7' ]

  unit-tests-full:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/_unittest.yml
    with:
      os: ubuntu-latest
      python-version: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.12', '3.11', '3.10', '3.9', '3.8', '3.7' ]
  
  unit-tests-fast:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/_unittest.yml
    with:
      os: ubuntu-latest
      python-version: '3.8'


  e2e-tests-full:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/_e2e.yml
    with:
      os: ubuntu-latest
      python-version: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.12', '3.11', '3.10', '3.9', '3.8', '3.7' ]
  
  e2e-tests-fast:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/_e2e.yml
    with:
      os: ubuntu-latest
      python-version: '3.8'

