name: '[run examples] Run example notebooks'

on: [push]
jobs:
  test-examples:
    runs-on: [ubuntu-latest, windows-latest]
    env:
      KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
      KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
    strategy:
      fail-fast: false
      matrix:
        # TODO
        # only run full suite on merge to main
        # run individual push on 3.7 kernel
        python-version: ['3.7'] # [ '3.10', '3.9', '3.8', '3.7' ]
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U .
        pip install -r requirements.txt
        pip install -r docs/requirements-doc.txt

    - name: Try compile sphinx and examples
      run: sphinx-build docs ./docs/build/
    
    - uses: actions/upload-artifact@v3
      with:
        name: docs-${{ matrix.python-version }}
        path: docs/build/