name: '[test] test siibra-paper notebooks'

on:
  push:
    branches: [ 'main', 'refactor_attr' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test_tutorials:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U .
          pip install -r requirements.txt
          pip install matplotlib
          pip install pytest nbmake
      
      - name: Run notebooks with nbmake
        run: pytest --nbmake --nbmake-timeout=1200 paper_notebookes
